run:
  concurrency: 4
  deadline: 5m
  issues-exit-code: 1

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  goimports:
    local-prefixes: goGit
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 40

linters:
  enable-all: true
  fast: false
  disable:
    - wrapcheck
    - gosec
    - exhaustivestruct
    - gci
    - scopelint
    - golint
    - maligned
    - interfacer